# Code Book for Coursera Getting and Cleaning Data Course Project

## Description of data and Variables

### This code book contains information describing the variables, the data, and transformations performed during the course of this project.

**The data were collected from the accelerometers from the Samsung Galaxy S smartphone and downloaded from UCI HAR Dataset.**

 The files used from the dataset included:
 
  1. features.txt
  2. train/X_train.txt
  3. test/X_test.txt
  4  train/subject_train.txt
  5. test/subject_test.txt
  6. train/y_train.txt
  7. test/y_test.txt
  
**The Variables used to create the tidy data set included:**

  1. subject - ID of partcipant
  2. activity - Activity type
  3. Mean and standard deviation of:
      * tBodyAcc-XYZ
      * tGravityAcc-XYZ
      * tBodyAccJerk-XYZ
      * tBodyGyro-XYZ
      * tBodyGyroJerk-XYZ
      * tBodyAccMag
      * tGravityAccMag
      * tBodyAccJerkMag
      * tBodyGyroMag
      * tBodyGyroJerkMag
      * fBodyAcc-XYZ
      * fBodyAccJerk-XYZ
      * fBodyGyro-XYZ
      * fBodyAccMag
      * fBodyAccJerkMag
      * fBodyGyroMag
      * fBodyGyroJerkMag

  * *'t' denotes time*
  * *'FFT' stands for Fast Fourier Transform*  
  * *'f' indicates frequency domain signals*
  * *'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.*

**The set of variables that were estimated from these signals are:**

   * mean(): Mean value
   * std(): Standard deviation
   * mad(): Median absolute deviation 
   * max(): Largest value in array
   * min(): Smallest value in array
   * sma(): Signal magnitude area
   * energy(): Energy measure. Sum of the squares divided by the number of values. 
   * iqr(): Interquartile range 
   * entropy(): Signal entropy
   * arCoeff(): Autorregresion coefficients with Burg order equal to 4
   * correlation(): correlation coefficient between two signals
   * maxInds(): index of the frequency component with largest magnitude
   * meanFreq(): Weighted average of the frequency components to obtain a mean frequency
   * skewness(): skewness of the frequency domain signal 
   * kurtosis(): kurtosis of the frequency domain signal 
   * bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window.
   * angle(): Angle between to vectors.

**Additional vectors obtained by averaging the signals in a signal window sample. These are used on the angle() variable:**

   * gravityMean
   * tBodyAccMean
   * tBodyAccJerkMean
   * tBodyGyroMean
   * tBodyGyroJerkMean

## Description of Script

**0. Load in needed packages and the files from the UCI HAR Dataset**

  * DataActivity_Test = y_test.txt
  * DataActivity_Train = y_train.txt
  * DataSubject_Train = subject_train.txt
  * DataSubject_Test = subject_test.txt
  * DataFeatures_Test = X_test.txt
  * DataFeatures_Train = X_train.txt
  * DataFeatures_Names = features.txt
    
**1. Merge and name data to create new dataset**

  * Data_Subject = (DataSubject_Train, DataSubject_Test)
  * Data_Activity = (DataActivity_Train, DataActivity_Test)
  * DataFeatures = DataFeatures_Train, DataFeatures_Test)
  * names(Data_Subject)
  * names(Data_Activity)
  * names(DataFeatures)
  * Data_Combine = (Data_Subject, Data_Activity)
  * Data = (DataFeatures, Data_Combine)
   
**2. Extracts only the measurements on the mean and standard deviation for each measurement**

  * FeaturesNames_Sub = Bring together all variables with the pattern mean and std
  * SelectedNames = create data set includeding only mean and std dev along with subject ID and activity
  * Data = pull together variable names and data to creat one data set of the mean and std
    
**3.Name activities in the dataset**

  * Activity_Labels = activity_labels.txt
    
**4.Adjusting for descriptive variable names**

  * "^t"into "time"
  * "^f" into "frequency"
  * "Acc" into "Accelerometer"
  * "Gyro" into "Gyroscope"
  * "Mag" into "Magnitude"
  * "BodyBody" into "Body"

**5. Creating Tidy Dataset**

  * Data2= subject, activity, Data, mean)
  * write.table(Data2, file = "tidydata.txt", row.name = FALSE)
